# Generated by Django 6.0.3 on 2026-05-11 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
        ('turnos', '0002_turno_unique_active_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario_email', models.EmailField(max_length=254)),
                ('destinatario_nombre', models.CharField(blank=True, max_length=160)),
                ('tipo', models.CharField(choices=[('turno_creado', 'Turno creado'), ('turno_confirmado', 'Turno confirmado'), ('turno_cancelado', 'Turno cancelado'), ('turno_completado', 'Turno completado'), ('turno_ausente', 'Turno ausente'), ('turno_reprogramado', 'Turno reprogramado')], max_length=30)),
                ('asunto', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('mensaje_error', models.TextField(blank=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_email', to='negocio.negocio')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_email', to='turnos.turno')),
            ],
            options={
                'verbose_name': 'Notificacion email',
                'verbose_name_plural': 'Notificaciones email',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['negocio', 'creado_en'], name='notificacio_negocio_126b90_idx'), models.Index(fields=['turno', 'creado_en'], name='notificacio_turno_i_cc4c76_idx'), models.Index(fields=['estado'], name='notificacio_estado_215a1f_idx'), models.Index(fields=['tipo'], name='notificacio_tipo_9f8c74_idx')],
            },
        ),
    ]
