# Generated by Django 6.0.3 on 2026-05-08 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
        ('profesional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('superadmin', 'Superadmin'), ('admin_negocio', 'Admin negocio'), ('recepcionista', 'Recepcionista'), ('profesional', 'Profesional')], default='recepcionista', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='negocio.negocio')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membresias_usuario', to='profesional.profesional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_negocio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de negocio',
                'verbose_name_plural': 'Miembros de negocio',
                'ordering': ['negocio', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'negocio'), name='uniq_miembro_user_negocio')],
            },
        ),
    ]
