# Generated by Django 6.0.3 on 2026-05-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(blank=True, max_length=120)),
                ('nombre_visible', models.CharField(blank=True, max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('tipo_documento', models.CharField(blank=True, choices=[('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('cuit', 'CUIT'), ('otro', 'Otro')], max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=40)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado')], default='activo', max_length=15)),
                ('acepta_recordatorios', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='negocio.negocio')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['negocio', 'apellido', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('negocio', 'slug'), name='uniq_cliente_slug_negocio')],
            },
        ),
    ]
