# Generated by Django 6.0.3 on 2026-05-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('negocio', '0001_initial'),
        ('profesional', '0001_initial'),
        ('servicio', '0001_initial'),
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('completado', 'Completado'), ('ausente', 'Ausente')], default='solicitado', max_length=20)),
                ('origen', models.CharField(choices=[('admin', 'Admin'), ('online', 'Online'), ('telefono', 'Telefono'), ('whatsapp', 'WhatsApp')], default='admin', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=250)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('cancelado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='clientes.cliente')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='negocio.negocio')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='profesional.profesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='servicio.servicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='sucursal.sucursal')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha_hora_inicio'],
                'indexes': [models.Index(fields=['negocio', 'fecha_hora_inicio'], name='turnos_turn_negocio_cb15e1_idx'), models.Index(fields=['sucursal', 'fecha_hora_inicio'], name='turnos_turn_sucursa_cbdf4d_idx'), models.Index(fields=['profesional', 'fecha_hora_inicio'], name='turnos_turn_profesi_e9ff5e_idx'), models.Index(fields=['cliente', 'fecha_hora_inicio'], name='turnos_turn_cliente_be3f57_idx'), models.Index(fields=['estado'], name='turnos_turn_estado_3fab1e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_hora_fin__gt', models.F('fecha_hora_inicio'))), name='ck_turno_fin_gt_ini'), models.UniqueConstraint(condition=models.Q(('estado', 'cancelado'), _negated=True), fields=('profesional', 'fecha_hora_inicio'), name='uniq_turno_prof_inicio_act')],
            },
        ),
    ]
