# Generated by Django 6.0.3 on 2026-05-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('tipo_negocio', models.CharField(choices=[('barberia', 'Barberia'), ('salon_belleza', 'Salon de belleza'), ('consultorio', 'Consultorio'), ('centro_estetico', 'Centro estetico'), ('estudio_profesional', 'Estudio profesional'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=15)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, max_length=250)),
                ('email_principal', models.EmailField(max_length=254)),
                ('telefono_principal', models.CharField(max_length=20)),
                ('whatsapp_principal', models.CharField(blank=True, max_length=20)),
                ('sitio_web', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=120)),
                ('direccion_principal', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(max_length=120)),
                ('provincia_estado', models.CharField(blank=True, max_length=120)),
                ('pais', models.CharField(max_length=120)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('zona_horaria', models.CharField(default='America/Argentina/Buenos_Aires', max_length=100)),
                ('moneda', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dolar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=3)),
                ('idioma', models.CharField(choices=[('es', 'Espanol'), ('en', 'English'), ('pt', 'Portugues')], default='es', max_length=2)),
                ('nombre_visible', models.CharField(blank=True, max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='negocios/logos/')),
                ('color_primario', models.CharField(blank=True, max_length=7)),
                ('color_secundario', models.CharField(blank=True, max_length=7)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['nombre'],
            },
        ),
    ]
