# Generated by Django 6.0.3 on 2026-05-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permite_reserva_online', models.BooleanField(default=True)),
                ('permite_cancelacion_online', models.BooleanField(default=True)),
                ('politica_confirmacion', models.CharField(choices=[('automatica', 'Automatica'), ('manual', 'Manual')], default='automatica', max_length=20)),
                ('anticipacion_minima_reserva_minutos', models.PositiveIntegerField(default=60)),
                ('anticipacion_maxima_reserva_dias', models.PositiveIntegerField(default=30)),
                ('tiempo_minimo_cancelacion_minutos', models.PositiveIntegerField(default=120)),
                ('buffer_default_minutos', models.PositiveSmallIntegerField(default=0)),
                ('intervalo_turnos_minutos', models.PositiveSmallIntegerField(default=15)),
                ('recordatorio_horas_antes', models.PositiveSmallIntegerField(default=24)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='negocio.negocio')),
            ],
            options={
                'verbose_name': 'Configuracion del negocio',
                'verbose_name_plural': 'Configuraciones de negocio',
                'constraints': [models.CheckConstraint(condition=models.Q(('anticipacion_maxima_reserva_dias__gt', 0)), name='ck_conf_ant_max_dias_pos'), models.CheckConstraint(condition=models.Q(('intervalo_turnos_minutos__gt', 0)), name='ck_conf_intervalo_pos')],
            },
        ),
    ]
