# Generated by Django 6.0.3 on 2026-05-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_negocio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='buffer_entre_turnos_minutos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='permite_turnos_pasados',
            field=models.BooleanField(default=False),
        ),
    ]
