# Generated by Django 6.0.3 on 2026-05-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('suspendida', 'Suspendida')], default='activa', max_length=15)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('motivo_cierre', models.CharField(blank=True, max_length=250)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=120)),
                ('provincia_estado', models.CharField(blank=True, max_length=120)),
                ('pais', models.CharField(max_length=120)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('referencia_direccion', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('zona_horaria', models.CharField(blank=True, max_length=100)),
                ('es_principal', models.BooleanField(default=False)),
                ('acepta_turnos', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='negocio.negocio')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['negocio', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('negocio', 'slug'), name='uniq_sucursal_slug_negocio')],
            },
        ),
    ]
