# Generated by Django 6.0.3 on 2026-05-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=15)),
                ('duracion_minutos', models.PositiveSmallIntegerField(default=30)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('visible_en_reserva_online', models.BooleanField(default=True)),
                ('orden_visualizacion', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='negocio.negocio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['negocio', 'orden_visualizacion', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('negocio', 'slug'), name='uniq_servicio_slug_negocio'), models.CheckConstraint(condition=models.Q(('duracion_minutos__gt', 0)), name='ck_servicio_duracion_pos'), models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='ck_servicio_precio_no_neg')],
            },
        ),
    ]
