# Generated by Django 6.0.3 on 2026-05-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='dias_semana',
            field=models.JSONField(default=list),
        ),
    ]
