# Generated by Django 6.0.3 on 2026-05-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
        ('profesional', '0001_initial'),
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcepcionAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cierre_negocio', 'Cierre del negocio'), ('cierre_sucursal', 'Cierre de sucursal'), ('ausencia_profesional', 'Ausencia profesional'), ('bloqueo_agenda', 'Bloqueo de agenda'), ('feriado', 'Feriado'), ('otro', 'Otro')], default='bloqueo_agenda', max_length=30)),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('bloquea_turnos', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='negocio.negocio')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='profesional.profesional')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='sucursal.sucursal')),
            ],
            options={
                'verbose_name': 'Excepcion de agenda',
                'verbose_name_plural': 'Excepciones de agenda',
                'ordering': ['negocio', 'fecha_hora_inicio'],
                'indexes': [models.Index(fields=['negocio', 'fecha_hora_inicio', 'fecha_hora_fin'], name='excepcion_e_negocio_dfe75e_idx'), models.Index(fields=['profesional', 'fecha_hora_inicio'], name='excepcion_e_profesi_064ab9_idx'), models.Index(fields=['sucursal', 'fecha_hora_inicio'], name='excepcion_e_sucursa_a54b63_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_hora_fin__gt', models.F('fecha_hora_inicio'))), name='ck_exc_fin_gt_ini')],
            },
        ),
    ]
