# Generated by Django 6.0.3 on 2026-05-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
        ('servicio', '0001_initial'),
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(blank=True, max_length=120)),
                ('nombre_visible', models.CharField(blank=True, max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('tipo_profesional', models.CharField(choices=[('barbero', 'Barbero'), ('estilista', 'Estilista'), ('medico', 'Medico'), ('esteticista', 'Esteticista'), ('profesional', 'Profesional'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('especialidad', models.CharField(blank=True, max_length=120)),
                ('matricula', models.CharField(blank=True, max_length=80)),
                ('descripcion_profesional', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=15)),
                ('acepta_turnos', models.BooleanField(default=True)),
                ('duracion_buffer_minutos', models.PositiveSmallIntegerField(default=0)),
                ('color_agenda', models.CharField(blank=True, max_length=7)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profesionales/fotos/')),
                ('visible_en_reserva_online', models.BooleanField(default=True)),
                ('orden_visualizacion', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='negocio.negocio')),
                ('servicios', models.ManyToManyField(blank=True, related_name='profesionales', to='servicio.servicio')),
                ('sucursales', models.ManyToManyField(blank=True, related_name='profesionales', to='sucursal.sucursal')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['negocio', 'orden_visualizacion', 'apellido', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('negocio', 'slug'), name='uniq_prof_slug_negocio')],
            },
        ),
    ]
