# Generated by Django 6.0.3 on 2026-05-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
        ('profesional', '0001_initial'),
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='negocio.negocio')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='profesional.profesional')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='sucursal.sucursal')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['negocio', 'sucursal', 'profesional', 'dia_semana', 'hora_inicio'],
                'indexes': [models.Index(fields=['negocio', 'dia_semana', 'activo'], name='disponibili_negocio_779ebc_idx'), models.Index(fields=['profesional', 'dia_semana', 'activo'], name='disponibili_profesi_b7f2b4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='ck_disp_hora_fin_gt_ini'), models.CheckConstraint(condition=models.Q(('fecha_hasta__isnull', True), ('fecha_desde__isnull', True), ('fecha_hasta__gte', models.F('fecha_desde')), _connector='OR'), name='ck_disp_fecha_fin_gte_ini')],
            },
        ),
    ]
